### ISSUE TITLE
Updated kernel

### ISSUE THREAD

**Issue by artem** [OnePlusOSS/android_kernel_oneplus_msm8974#1]
@leonfish77101 Oxygen OS 3.x has released for Oneplus X and H2OS 2.x has released both for Oneplus X and Oneplus One, so, can you upload updated kernel sources for MSM8974 platform, please? Thanks!

**Comment by leonfish77101** [comment]
@ab123321 The build we have been released is only for the community, that means the build, especially kernel, is not a stable one. We will release all 8974 M kernel codes once the kernel is stable

**Comment by YumeMichi** [comment]
@leonfish77101 That's really good news.

**Comment by ashwinr64** [comment]
@leonfish77101 Now that the OTA is released , could you give an ETA for kernel sources for OnePlus X.

**Comment by sundhar88** [comment]
Release the updated kernel already. Many devs waiting for it. Quick Please!

**Comment by EyeCantCU** [comment]
@ashwinr64 were I you, I would use CAs sources as a base and just add the DTS yourself. Authorship doesn't seem to be important here
