### ISSUE TITLE
Broken kernel 

### ISSUE THREAD

**Issue by andreaturchet** [OnePlusOSS/android_kernel_oneplus_msm8974#2]
Hi, just cloned 6.0.1 opx kernel and tried to build with GCC-4.8 on ubuntu16.06, but it doesn't compile, a lots of errors.
Can you release please an unbroken kernel ? Thanks.

**Comment by Xoib** [comment]
First, can you please provide your errors, at least.

**Comment by leonfish77101** [comment]
@andreturket Can you paste the build errors here?

**Comment by scafroglia93** [comment]
@leonfish77101 You have released a rotten kernel, it seems to me that the GPL undertake to release a fully functional kernel. Let's not kid

**Comment by brucechiu1113** [comment]
@andreturket 
Did you meet the build error below:
Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at /home/brucechiu/android/8974/MSM8974/android/kernel/kernel/timeconst.pl line 373.
/home/brucechiu/android/8974/MSM8974/android/kernel/kernel/Makefile:129: recipe for target 'kernel/timeconst.h' failed

If so, I met the same error while I used Ubuntu 16.04 with GNU Make 4.1 as build environment.
After I use GNU Make 3.81 instead, it can build passed.

If you didn't meet this build error, please paste the build errors. Thanks.

**Comment by EyeCantCU** [comment]
@andreturket @brucechiu1113 Pick this from my GitHub. timeconst.pl is not optimal anymore:

https://github.com/RJDTWO/android_kernel_oneplus_onyx/commit/dae026718a949d5eb7c83a95c783422c8f41f2b2

@leonfish77101 I am going to have to agree with @scafroglia93 on this one... Its great you guys are trying your best to be open source, but I am certain that the mass commit where you added everything is missing proper credit which is shameful. How hard would it have been to have kept it open? Sultan and I do it... Why can't you guys? Can a 16 year old blind guy seriously be more qualified? Come on. Give me your pay check and I will do your job, because it is obvious that you guys cant. Again, I appreciate it, but do it right. Thank you... 

One more thing, why didn't you guys base on top of LA.BF.1.1.3-01610-8x74.0 from the 5th of May? Why LA.BF.1.1.3-01310-8x74.0 from April? Its a simple merge. I did it myself

**Comment by ashwinr64** [comment]
Oh please ! There isn't any reason for you to be so rude. It's really hard to see OEMs releasing their sources . But OnePlus has always been very developer friendly . Great Job OnePlus. This kernel is absolutely functional . And all the other parts open sourced are also seem to be working . I do accept that there are a few kinks if built from the manifest provided , but yeah it isn't a big deal to solve.

**Comment by EyeCantCU** [comment]
@ashwinr64 Considering no one else was going to take the time to help these two, I wouldn't consider that to be rude, no.

I think I am entitled to speak on behalf of all of the work that other developers have contributed themselves. I don't think its right for OnePlus to be able to get away with it when it isn't a motive of open source nature. 

The source is great. Don't get me wrong. I appreciate it... But how would you feel if someone were to be freeloading off of your work without credit? Not too good I'd imagine.

At the end of the day though, they are a company just like every other.

**Comment by scafroglia93** [comment]
In this case Oneplus violated license GPL

**Comment by scafroglia93** [comment]
@ashwinr64 Even elephone, Huawei and Zuk to name a few competitors release the kernel only it's broken and you can not compile. The regulations indicate that GPL should be released the complete material and not part. Never mind the speeches by fanboy or fond OnePlus. By chance you ever seen the Linux Kernel (Kernel.org) released with the missing parts? I think not

**Comment by EyeCantCU** [comment]
@scafroglia93 The thing is,  there isn't really anything broken.  OnePlus is amazing when it comes to that.  Just had to replace the older Pl script with a be one and fix one or two inclusions.  No big deal though. 

The kernel here has everything we need  I just compiled it myself.  You can grab my source here if you'd like:

https://github.com/RJDTWO/android_kernel_oneplus_msm8974

Either way,  I think @ashwinr64 is right to a degree.  The only other company that does anything like this is Google.  I just wish they would maintain authorship.. 

Anyway,  I sincerely apologize if I offended anyone here.  That's just how I feel.  It doesn't seem right to rake credit for work that isn't yours

**Comment by EyeCantCU** [comment]
I'd recommend closing this @leonfish77101

Just a few people complaining over nothing.  My pull request fixes the build errors anyway
